name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: githubrunnerset
    steps:
      - name: Check runner context
        run: |
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner arch: $RUNNER_ARCH"
          echo "Job is running on: $(hostname)"
          echo "Current user: $(whoami)"
          echo "Working dir: $(pwd)"
          echo "Disk usage:"
          df -h

      - name: Run basic command
        run: echo "✅ Hello from your self-hosted runner!"

      - name: List files
        run: ls -la

      - name: Print environment variables
        run: env | sort
