name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: githubrunnerset
    steps:
      - name: Context
        run: |
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          cat /etc/os-release
          echo "Runner arch: $RUNNER_ARCH"
          echo "Job is running on: $(hostname)"
          echo "Current user: $(whoami)"
          echo "Working dir: $(pwd)"
          echo "Disk usage:"
          df -h

      - name: Basic
        run: |
          echo "Hello from your self-hosted runner!"

      - name: File
        run: |
          echo 'hello world!' > test.txt
          ls
          cat test.txt

      - name: Envar
        run: |
          export TEST_ENV=hello
          env | grep TEST_ENV
          env

      - name: Install
        run: |
          set +e
          cat /home/runner/safe_sleep.sh
          #sudo apt-get update 
          #ls -l /usr/bin/sudo
          #chmod 4755 /usr/bin/sudo
          #ls -l /usr/bin/sudo
          #curl -s https://jsonplaceholder.typicode.com/todos/1 | jq '.title'
          ##apt-get update #> /dev/null 2>&1
          #apt-get install -y nodejs npm
          #echo '--- --- ---'
          #sudo apt-get update  #> /dev/null 2>&1
          #sudo apt-get install -y nodejs npm
          #node --version
          curl -s -X POST https://jsonplaceholder.typicode.com/posts \
          -H "Content-Type: application/json" \
          -d '{"title":"foo","body":"bar","userId":1}'
          cat /home/runner/run.sh


      - name: FIPS
        run: |
          echo 'FIPS test'
          cat /proc/sys/crypto/fips_enabled 2>/dev/null || echo 0
          echo 'FIPS DONE'

