name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: githubrunnerset
    steps:
      - name: Context
        run: |
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner arch: $RUNNER_ARCH"
          echo "Job is running on: $(hostname)"
          echo "Current user: $(whoami)"
          echo "Working dir: $(pwd)"
          echo "Disk usage:"
          df -h

      - name: Basic
        run: |
          echo "Hello from your self-hosted runner!"
          python --version
          node --version
        

      - name: File
        run: |
          echo 'hello world!' > test.txt
          ls
          cat test.txt

      - name: Envar
        run: |
          export TEST_ENV=hello
          env | grep TEST_ENV

      - name: FIPS
        run: |
          echo 'FIPS test'
          openssl version

